= January 2025
:icons: font

In January 2025

* We continued our work on the xref:../../../epics/77-maven-due-diligence/index.adoc[due-diligence] we started in xref:../../2024/12/index.adoc[December 2024].
Several pull requests to re-enable Maven builds of components that are part of the reactor build were created, approved and merged by the Maven committers.
This was a first step to establish trust into our quality improvements.
* Additionally, we could start on the first original work package epic, the xref:../../../epics/44-migrate-to-maven-di/index.adoc[migration of Plexus containers to Maven DI] (dependency injection).
For historic reasons, Maven was dependent on several versions of external dependency injection frameworks.
These frameworks either lack active maintenance, or other organizations control the development of these frameworks.
Both circumstances result in a risk to further development.
Hence, the Maven team has a strong demand to eliminate at least the oldest and most remote dependencies, aiming towards a unique solution for dependency injection.
