#!/bin/bash

set -euo pipefail

: "${REPO_NAME=support-and-care/maven-support-and-care}"
: "${GITHUB_TOKEN=you-need-to-set-this}"

artifact_name="${1}"

# Fetch artifacts
response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github+json" \
  "https://api.github.com/repos/$REPO_NAME/actions/artifacts")

# Check if the artifact exists
if echo "$response" | jq -e --arg name "$artifact_name" '.artifacts[].name | select(. == $name)' > /dev/null; then
  echo "Artifact '$artifact_name' exists."
  exit 0
else
  echo "Artifact '$artifact_name' does not exist."
  exit 1
fi