#!/bin/bash

set -euo pipefail

: "${REPO_NAME=support-and-care/maven-support-and-care}"
: "${WORKFLOW_TRIGGER_TOKEN=${GITHUB_TOKEN:-you-need-to-set-this}}"
: "${CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)}}"

if [[ "${ACTIONS_STEP_DEBUG:-}" == "true" ]]; then
  set -vx
fi

workflow_name="${1:-}"

if [[ -z "${workflow_name}" ]]; then
  echo "Error: Workflow name is required as a parameter." >&2
  exit 1
fi

debug () {
  if [[ "${ACTIONS_STEP_DEBUG:-}" == "true" ]]; then
    echo "$@" >&2
  fi
}

# Trigger the workflow
response=$(curl -s -X POST -H "Authorization: Bearer ${WORKFLOW_TRIGGER_TOKEN}" \
  -H "Accept: application/vnd.github+json" \
  -d "{\"ref\":\"${CURRENT_BRANCH}\"}" \
  "https://api.github.com/repos/${REPO_NAME}/actions/workflows/${workflow_name}/dispatches")

if [[ $? -eq 0 ]]; then
  debug "Successfully triggered workflow '${workflow_name}' on branch '${CURRENT_BRANCH}'."
  echo "Workflow triggered successfully."
else
  echo "Failed to trigger workflow '${workflow_name}' on branch '${CURRENT_BRANCH}'." >&2
  exit 1
fi