jqassistant:
  repositories:
    local: ~/.jqassistant/repository
  plugins:
#    - group-id: net.aschemann.jqassistant.plugins
#      artifact-id: jqa-groovy-plugin
#      version: 0.2.0-SNAPSHOT
    - group-id: de.kontext-e.jqassistant.plugin
      artifact-id: jqassistant.plugin.git
      version: 2.4.0
    - group-id: org.jqassistant.plugin
      artifact-id: jqassistant-github-plugin
      version: 1.2.0-M1
    - group-id: org.jqassistant.plugin
      artifact-id: jqassistant-jira-plugin
      version: GAsc-1.0.0-SNAPSHOT
  analyze:
    rule:
      directory: jqassistant/rules/
    groups:
      - Team
      - Epics
      - Issues
    report:
      fail-on-severity: blocker
  scan:
    continue-on-error: true
    properties:
      directory.follow-symbolic-links: true
      maven3.dependencies.scan: true
#      jira.custom.issue.fields: <custom field name(s)
      # KJARSIGNER -> MJARSIGNER
      jira.projects: ARCHETYPE,DOXIA,DOXIASITETOOLS,DOXIATOOLS,JXR,MJARSIGNER,MACR,MANTRUN,MARCHETYPES,MARTIFACT,MASFRES,MASSEMBLY,MBUILDCACHE,MCHANGELOG,MCHANGES,MCHECKSTYLE,MCLEAN,MCOMPILER,MDEP,MDEPLOY,MDOAP,MEAR,MEJB,MENFORCER,MGPG,MINDEXER,MINSTALL,MINVOKER,MJAR,MJAVADOC,MJDEPRSCAN,MJDEPS,MJLINK,MJMOD,MLINKCHECK,MNG,MNGSITE,MPH,MPIR,MPLUGIN,MPLUGINTESTING,MPMD,MPOM,MRAR,MRELEASE,MRESOLVER,MRESOLVER,MRESOURCES,MRRESOURCES,MSCMPUB,MSCRIPTING,MSHADE,MSHARED,MSITE,MSKINS,MSOURCES,MSTAGE,MTOOLCHAINS,MVERIFIER,MWAR,MWRAPPER,SCM,SUREFIRE,WAGON

    include:
#      files:
#        - 
#        - src
#        - README.adoc
      urls:
        - jira:server::https://issues.apache.org/jira

        - github:repository::https://github.com/support-and-care/maven-support-and-care

        - github:repository::https://github.com/apache/maven-site
#        - github:repository::https://github.com/apache/maven-sources
#        - github:repository::https://github.com/apache/maven-build-cache-extension
#        - github:repository::https://github.com/apache/maven
#        - github:repository::https://github.com/apache/maven-mvnd
#        - github:repository::https://github.com/apache/maven-integration-testing
#        - github:repository::https://github.com/apache/maven-resolver
#        - github:repository::https://github.com/apache/maven-resolver-ant-tasks
#        - github:repository::https://github.com/apache/maven-wrapper
#        - github:repository::https://github.com/apache/maven-clean-plugin
#        - github:repository::https://github.com/apache/maven-compiler-plugin
#        - github:repository::https://github.com/apache/maven-deploy-plugin
#        - github:repository::https://github.com/apache/maven-install-plugin
#        - github:repository::https://github.com/apache/maven-resources-plugin
#        - github:repository::https://github.com/apache/maven-site-plugin
#        - github:repository::https://github.com/apache/maven-surefire
#        - github:repository::https://github.com/apache/maven-verifier-plugin
#        - github:repository::https://github.com/apache/maven-ear-plugin
#        - github:repository::https://github.com/apache/maven-ejb-plugin
#        - github:repository::https://github.com/apache/maven-jar-plugin
#        - github:repository::https://github.com/apache/maven-rar-plugin
#        - github:repository::https://github.com/apache/maven-war-plugin
#        - github:repository::https://github.com/apache/maven-acr-plugin
#        - github:repository::https://github.com/apache/maven-shade-plugin
#        - github:repository::https://github.com/apache/maven-source-plugin
#        - github:repository::https://github.com/apache/maven-jlink-plugin
#        - github:repository::https://github.com/apache/maven-jmod-plugin
#        - github:repository::https://github.com/apache/maven-changelog-plugin
#        - github:repository::https://github.com/apache/maven-changes-plugin
#        - github:repository::https://github.com/apache/maven-checkstyle-plugin
#        - github:repository::https://github.com/apache/maven-doap-plugin
#        - github:repository::https://github.com/apache/maven-javadoc-plugin
#        - github:repository::https://github.com/apache/maven-jdeps-plugin
#        - github:repository::https://github.com/apache/maven-jxr
#        - github:repository::https://github.com/apache/maven-linkcheck-plugin
#        - github:repository::https://github.com/apache/maven-pmd-plugin
#        - github:repository::https://github.com/apache/maven-project-info-reports-plugin
#        - github:repository::https://github.com/apache/maven-antrun-plugin
#        - github:repository::https://github.com/apache/maven-archetype
#        - github:repository::https://github.com/apache/maven-artifact-plugin
#        - github:repository::https://github.com/apache/maven-assembly-plugin
#        - github:repository::https://github.com/apache/maven-dependency-plugin
#        - github:repository::https://github.com/apache/maven-enforcer
#        - github:repository::https://github.com/apache/maven-gpg-plugin
#        - github:repository::https://github.com/apache/maven-help-plugin
#        - github:repository::https://github.com/apache/maven-invoker-plugin
#        - github:repository::https://github.com/apache/maven-jarsigner-plugin
#        - github:repository::https://github.com/apache/maven-jdeprscan-plugin
#        - github:repository::https://github.com/apache/maven-plugin-tools
#        - github:repository::https://github.com/apache/maven-release
#        - github:repository::https://github.com/apache/maven-scm
#        - github:repository::https://github.com/apache/maven-scm-publish-plugin
#        - github:repository::https://github.com/apache/maven-scripting-plugin
#        - github:repository::https://github.com/apache/maven-stage-plugin
#        - github:repository::https://github.com/apache/maven-toolchains-plugin
#        - github:repository::https://github.com/apache/maven-archiver
#        - github:repository::https://github.com/apache/maven-artifact-transfer
#        - github:repository::https://github.com/apache/maven-common-artifact-filters
#        - github:repository::https://github.com/apache/maven-dependency-analyzer
#        - github:repository::https://github.com/apache/maven-dependency-tree
#        - github:repository::https://github.com/apache/maven-file-management
#        - github:repository::https://github.com/apache/maven-filtering
#        - github:repository::https://github.com/apache/maven-invoker
#        - github:repository::https://github.com/apache/maven-jarsigner
#        - github:repository::https://github.com/apache/maven-mapping
#        - github:repository::https://github.com/apache/maven-project-utils
#        - github:repository::https://github.com/apache/maven-reporting-api
#        - github:repository::https://github.com/apache/maven-reporting-exec
#        - github:repository::https://github.com/apache/maven-reporting-impl
#        - github:repository::https://github.com/apache/maven-script-interpreter
#        - github:repository::https://github.com/apache/maven-shared-incremental
#        - github:repository::https://github.com/apache/maven-shared-io
#        - github:repository::https://github.com/apache/maven-shared-jar
#        - github:repository::https://github.com/apache/maven-shared-resources
#        - github:repository::https://github.com/apache/maven-shared-utils
#        - github:repository::https://github.com/apache/maven-verifier
#        - github:repository::https://github.com/apache/maven-doxia
#        - github:repository::https://github.com/apache/maven-doxia-site
#        - github:repository::https://github.com/apache/maven-doxia-sitetools
#        - github:repository::https://github.com/apache/maven-doxia-book-maven-plugin
#        - github:repository::https://github.com/apache/maven-doxia-book-renderer
#        - github:repository::https://github.com/apache/maven-doxia-converter
#        - github:repository::https://github.com/apache/maven-doxia-linkcheck
#        - github:repository::https://github.com/apache/maven-archetypes
#        - github:repository::https://github.com/apache/maven-parent
#        - github:repository::https://github.com/apache/maven-apache-parent
#        - github:repository::https://github.com/apache/maven-apache-resources
#        - github:repository::https://github.com/apache/maven-default-skin
#        - github:repository::https://github.com/apache/maven-fluido-skin
#        - github:repository::https://github.com/apache/maven-dist-tool
#        - github:repository::https://github.com/apache/maven-gh-actions-shared
#        - github:repository::https://github.com/apache/maven-jenkins-env
#        - github:repository::https://github.com/apache/maven-jenkins-lib
#        - github:repository::https://github.com/apache/maven-indexer
#        - github:repository::https://github.com/apache/maven-plugin-testing
#        - github:repository::https://github.com/apache/maven-wagon
#        - github:repository::https://github.com/apache/maven-studies
#
#        - github:repository::https://github.com/apache/maven-repository-tools
#        - github:repository::https://github.com/apache/maven-sandbox
#        - github:repository::https://github.com/apache/maven-doxia-ide
#
#        - github:repository::https://github.com/codehaus-plexus/codehaus-plexus.github.io
#        - github:repository::https://github.com/codehaus-plexus/modello
#        - github:repository::https://github.com/codehaus-plexus/plexus-classworlds
#        - github:repository::https://github.com/codehaus-plexus/plexus-archiver
#        - github:repository::https://github.com/codehaus-plexus/plexus-cipher
#        - github:repository::https://github.com/codehaus-plexus/plexus-cli
#        - github:repository::https://github.com/codehaus-plexus/plexus-compiler
#        - github:repository::https://github.com/codehaus-plexus/plexus-digest
#        - github:repository::https://github.com/codehaus-plexus/plexus-i18n
#        - github:repository::https://github.com/codehaus-plexus/plexus-interactivity.git'
#        - github:repository::https://github.com/codehaus-plexus/plexus-interpolation.git'
#        - github:repository::https://github.com/codehaus-plexus/plexus-io
#        - github:repository::https://github.com/codehaus-plexus/plexus-languages
#        - github:repository::https://github.com/codehaus-plexus/plexus-resources
#        - github:repository::https://github.com/codehaus-plexus/plexus-sec-dispatcher
#        - github:repository::https://github.com/codehaus-plexus/plexus-swizzle
#        - github:repository::https://github.com/codehaus-plexus/plexus-velocity
#        - github:repository::https://github.com/codehaus-plexus/plexus-containers
#        - github:repository::https://github.com/codehaus-plexus/plexus-components
#        - github:repository::https://github.com/codehaus-plexus/plexus-pom
#        - github:repository::https://github.com/codehaus-plexus/plexus-testing
#        - github:repository::https://github.com/codehaus-plexus/plexus-utils
#        - github:repository::https://github.com/codehaus-plexus/plexus-xml
#
#        - github:repository::https://github.com/eclipse-sisu/sisu-project

#  scan:
#    ...
#    include:
#      by-plugin:
#        github:repository:
#          defaults:
#            prs: false
#            issues: false
#            commits: false
#            branches: false
#            branchPattern: '(main|master|develop)'
#            tags: false
#            tagPattern: 'release/.*'
#          repositories:
#          - url: https://github.com/support-and-care/maven-support-and-care
#            prs: true
#            issues: true
#            tags: true
#            commits: true
#            branches: true
#          - url: https://github.com/apache/maven-site
#            prs: true
#            issues: false
#            commits: false
#
