= Support &amp; Care for Apache Maven&trade;
:icons: font
:toc: left

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

This repository is used to track the work of https://open-elements.com/support-care-maven/[Support &amp; Care for Apache Maven&trade;] as open and transparent as possible.

The *Support &amp; Care for Maven* Initiative is a groundbreaking program to help secure the future of the https://maven.apache.org/[Apache Maven&trade; project] through sustainable support and care.
The initiative aims to strengthen the development and maintenance of Maven&trade; through funding of necessary contributions to the project, thus ensuring the high quality and availability of Apache Maven&trade; that the Java ecosystem needs.

== Our Mission

Apache Maven&trade; is a critical tool in the Java ecosystem, used by millions of developers worldwide with &gt;100 million downloads per year.
Despite its importance, Maven&trade; is maintained primarily on a volunteer basis with no fixed financial support.
Our mission is to create a sustainable source of funding for highly necessary work around the Apache Maven&trade; project and direct contribution to the project.
Our goal is to enable continuous improvements and professional support for Maven&trade;.

== How we work

* *Funding by a fund:* The fund provides the necessary resources to finance critical development work on Apache Maven&trade;.
* *Transparent use of funds:* Open Elements manages funding transparently and reports regularly on the progress of milestones.
* *Development by experts:* Our work is carried out by leading Maven&trade; experts.

For more details, see https://open-elements.com/support-care-maven/[our public page].

== Workflow (Epics)

Before we decided on what topics we would spend money on, we started several discussions with the Apache Maven&trade; team.
You can find all that in the https://github.com/OpenElements/maven-support-care/discussions[discussions section] of this repository.
We extracted epic issues based on the discussions in xref:epics.adoc[Epics].

== Next steps

We currently specify and estimate the epics that should be funded.
All that epics will be managed as https://github.com/support-and-care/maven-support-and-care/issues?q=is%3Aopen+is%3Aissue+label%3Aepic[issues (with label _Epic_)] in this repository.

[IMPORTANT]
====
It is not our plan to ignore the https://maven.apache.org/issue-management.html[Maven&trade; issue trackers] nor https://maven.apache.org/guides/development/guide-helping.html[Maven&trade; contribution guidelines].
All issues that are based on the milestones that we will define in the face-2-face meeting will be handled in the Maven&trade; issue trackers and associated work will be reviewed by the wider community before merging.
This repository is used to show the work done by using the given funds as transparent as possible.
====

== About us

Support &amp; care for Apache Maven&trade; is supported by both companies and individual community members.
Even though the initiative is managed and led by https://open-elements.com[Open Elements], everyone involved works 100% on an equal footing.
In addition to Open Elements, the French-based company https://www.yupiik.com[Yupiik], which specializes in the development of open source software, is also involved.

In addition to these companies, individuals who are committed to the future of Apache Maven&trade; are also involved.
These community members are experts in the field of Maven&trade; and contribute their experience and knowledge to the initiative.

== Contribute

We invite developers and interested parties to participate in the initiative, provide feedback and become part of our community.
Contact us at link:mailto:maven@open-elements.com[maven@open-elements.com] for more information and how you can contribute.

== Trademark

Apache&trade; and Apache Maven&trade; are trademarks of The Apache Software Foundation.