= May 2025
:icons: font

== Work Package 1 — Security of the Supply Chain

* We setup an instance of Dependencytrack to compare it to ORT

== Work Package 2 — Maintenance

* We helped to test further Jira projects migration (MDOAP, MJDEPS, MLINKCHECK, MJDEPRSCAN, MSCMPUB,  MSCRIPTING, MJARSIGNER, SUREFIRE, MEAR, MINVOKER, MJAR).
* We find a solution how to migration big jira projects.
* Further Jira projects were migrated to GitHub issues (MEJB, MACR, MJMOD)
* We refactored parts of the Maven Dependency Plugin to improve the build process and code quality.
* We upgraded dependencies in the Maven Build Cache Extension to improve security and compatibility.
* We analyzed issues between MBUILDCACHE and protobuf-maven-plugin.

== Work Package 3 — Modernisation of Core Feature

No work performed

== Work Package 4 — Documentation

* Aligned site documentation with Maven source projects (removed outdated components, updated package diagrams, improved build processes).
* Finished the first iteration of documentation about Maven DI.
* Fix small documentation issues.
* Started a suggestion what a better structure for user documentation and plugin developer documentation could look like.
