name: Scan with jQAssistant

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      run_scan:
        description: 'Run jQAssistant scan (force)'
        type: boolean
        required: false
        default: false        

permissions:
  contents: read
  id-token: write

jobs:
  jqa-scan:
    runs-on: ubuntu-latest
    env:
      GITHUB_LOGIN: ${{ github.repository_owner }}
      # We need both environment variables for the GitHub API and the jQA GitHub plugin
      GITHUB_OAUTH: ${{ github.token }}
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run jQAssistant scan
        id: jqa_scan
        run: |
          if .github/check-artifact "jqassistant-store"; then
            echo "Artifact already exists, skipping scan."
            echo "should_analyze=false" >> $GITHUB_OUTPUT
          else
            echo "Artifact does not exist, proceeding with scan."
            mvn jqassistant:scan -fae -e -ntp -s .github/settings.xml
            echo "should_analyze=true" >> $GITHUB_OUTPUT
          fi

      - name: Upload jqassistant/store artifact
        uses: actions/upload-artifact@v4
        if: steps.jqa_scan.outputs.should_analyze == 'true'
        with:
          name: jqassistant-store
          path: target/jqassistant/store

      - name: Trigger analysis workflow
        if: ${{ steps.jqa_scan.outputs.should_analyze == 'true' || inputs.run_scan == 'true' }}
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'jqa-analyze.yaml',
              ref: context.ref,
              inputs: {
                workflow_run_id: context.runId.toString()
              }
            })
          

