name: Analyze with jQAssistant

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  jqa-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Download jqassistant/store artifact
        uses: actions/download-artifact@v4
        with:
          name: jqassistant-store
          path: target/jqassistant/store

      - name: Run jQAssistant analyze and generate docs
        id: jqa_analyze
        run: mvn jqassistant:analyze asciidoctor:process-asciidoc -fae -e -ntp -s .github/settings.xml

      - name: Upload Generated Documentation
        uses: actions/upload-artifact@v4
        with:
          name: generated-docs
          path: target/generated-docs

      - name: Trigger publication workflow
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'publish-docs.yaml',
              ref: context.ref
            })
