name: Publish Documentation

on:
  push:
  workflow_dispatch:
    inputs:
      publish_docs:
        description: 'Publish documents to GitHub Pages (force)'
        type: boolean
        required: false
        default: false

permissions:
  pages: write
  id-token: write

jobs:
  publish-docs:
    if: ${{ inputs.publish_docs || github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Check for generated-docs artifact
        run: |
          if .github/check-artifact "generated-docs"; then
            echo "Artifact exists, proceeding with analysis."
          else
            echo "Artifact does not exist, you have to 'scan' first!" >&2
            echo "::error::Missing generated-docs artifact"
            exit 0
          fi

      - name: Download generated-docs artifact
        run: |
          .github/download-artifact generated-docs target/generated-docs
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/generated-docs
      
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
